services:
  - type: web
    name: scalable-url-shortener
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: BASE_URL
        value: https://scalable-url-shortener.onrender.com

      - key: DATABASE_URL
        fromDatabase:
          name: urlshortener-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: urlshortener-redis
          property: connectionString

databases:
  - name: urlshortener-db
    plan: free
    databaseName: urlshortener
    user: postgres

services:
  - type: keyvalue
    name: urlshortener-redis
    plan: free